### ISSUE TITLE
模型导入

### ISSUE THREAD

**Issue by zhy8602099** [MoritzWillig/pysnic#1]
我最近在做超像素分割的项目，看到了您的代码，很感兴趣，您能提供一下_init_文件么，我在运行程序时，无法导入模型

**Comment by MoritzWillig** [comment]
Hey, I'm not quite sure if I understood your problem correctly. I must admit, that I haven't written an explicit ``__init__`` file yet, but only worked with the different classes directly. You can find examples, under pysnic/examples/

If you have any suggestions regarding the improvement of the project structure, let me know!

**Comment by zhy8602099** [comment]
谢谢您的回复，我在电脑上安装了setup.py后，运行了pysnic / examples /下的示例后，显示找不到pysnic.algorithms模型，之后我将所有的程序放入一个文件夹后，更改了import命令，解决了这个问题。

**Comment by MoritzWillig** [comment]
PySNIC can now be installed via pip:
```
pip install pysnic
```
